
package org.example.superfoodsservice;

import javax.xml.ws.Endpoint;

import com.willcode4coffee.webservice.implementation.SuperFoodsServiceSOAPImpl;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-01-09T13:10:32.508-06:00
 * Generated source version: 3.1.3
 * 
 */
 
public class SuperFoodsService_SuperFoodsServiceSOAP_Server{

    protected SuperFoodsService_SuperFoodsServiceSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SuperFoodsServiceSOAPImpl();
        String address = "http://www.example.org/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SuperFoodsService_SuperFoodsServiceSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
